### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by EnricoAC** [Maproom/qmapshack#135]
Hi everyone. I am new here and I am not sure this is the correct place for my inquiry, if not I apologize.

I am using QMapShack since few days and today the software freezed in a random moment. Unfortunately I cannot remember exactly what I was doing at the moment. I failed to stop the software even with ctrl-alt-canc, so I rebooted the pc. After reboot QMS won't start, freezing at the initial splashscreen. I unistalled and reinstalled QMS (last version) and still it is freezing at splashscreen (never actually entered). I tried to use the -f option to get a log, which you can find attached.

I am using QMS 1.14.0 on Win 10.

Thanks in advance to whoever can help me.
Enrico

[org.qlandkarte.QMapShack.log](https://github.com/Maproom/qmapshack/files/4390750/org.qlandkarte.QMapShack.log)

**Comment by kiozen** [comment]
Please use the templates provided:
https://github.com/Maproom/qmapshack/wiki/DocFaqProjectSite
This issue is closed because it does not use templates.

QMapShack seems to wait for online DEM data. If you rename this file:
C:/Users/enric/OneDrive/Future/GIS/QMapShack/DEM/Online_EUROPE_EU-DEM_25m.vrt
it should start again quickly. If not clean the registry from QMapShack settings.

**Comment by EnricoAC** [comment]
Thanks, cleaning the registry worked just fine.
I apologize for not using the template, next time I will.

Enrico

Il giorno ven 27 mar 2020 alle ore 07:33 Kiozen <notifications@github.com>
ha scritto:
