### ISSUE TITLE
Request to unmount systemdrive on startup

### ISSUE THREAD

**Issue by semidark** [Maproom/qmapshack#156]
When starting qmapshack 1.14.1.develop under my Ubuntu 18.04 i get asked by the system if i want to unmount my rootfs. 

**To Reproduce**
1. Compile qmapshack 1.14.1.develop
2. run mapshack as normal desktop User
3. Authorisation Dialog for unmounting  pops up

**Expected behavior**
There is no reason i can think of why qmapshack should trigger such an unmount

**Screenshots**
![grafik](https://user-images.githubusercontent.com/5747735/79684541-9059c780-8232-11ea-9f55-0f8f7e097927.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04.4
 - QMapShack Version 1.14.1.develop

**Comment by kiozen** [comment]
QMapShack probes all block devices for GPS devices by mounting them, analyzing their file structure and unmounting them again. This is also done for devices containing the system, as there is no way to differentiate. Usually the unmount for system drives is expected to fail. Probably your window manager interferes and asks for authorization. Don't ask me why it does. On most systems it does not, which is what I would expect.

You are welcome to come up with another method to reliably detect and handle GPS devices.

**Comment by JFritzle** [comment]
Don't know when I noticed same issue first time. But I am quite sure, it happened already several QMapShack versions before, maybe even after upgrading Ubuntu from version 16.04 to version 18.04.

Reason is a Linux security policy found in file
 `/usr/share/polkit-1/actions/org.freedesktop.UDisks2.policy`

Following modification prevents from being asked for authorization:
1. Open file in editor
2. Locate definition of action `org.freedesktop.udisks2.filesystem-unmount-others`, starting at line `<action id="org.freedesktop.udisks2.filesystem-unmount-others">`
3. Locate end of that action at subsequent line `</action>` 
4. Replace line `<allow_active>auth_admin_keep</allow_active>` by line `<allow_active>yes</allow_active>` located 2 lines before end of action

Do not forget to backup original file!

**Comment by JFritzle** [comment]
Concerning "You are welcome to come up with another method to reliably detect and handle GPS devices."

Maybe following (untested) modification of probing block devices could help:
Before mounting a device, e.g. `/dev/sda1`, one could ask Linux kernel if device is already mounted. This can be easily done by reading `/proc/mounts` line by line and check for existing mount point. If mount point aleady exists, existing mount point can be used for analyzing its file structure. Mounting and unmounting then were not necessary.

**Comment by kiozen** [comment]
Probing `/proc/mounts` you can do on some private hacky shell scripts but not on software that runs on a complete zoo of systems.

I added a probe for removable devices. Let's see what is broken by that.

**Comment by Markus-N** [comment]
Is there any chance this can be reopened ? Being a new user, I just stumbled on this issue.

Probing all block devices has some more side effects like waking up sleeping drives.  
I have my OS and most data used daily on an SSD and additionally five HDDs in a RAID (on my PC) and one HDD (on my Laptop). So the HDDs will sleep most time on both computers. I'd like to minimize the things that can wake them up except when I explicitly want to access the data on them.

I'd like to make a few suggestions for this issue:

1. Instead of probing everything, the device(s) could be configured explicitly. There is already a lot of configuring necessary for getting started, so having to configure the devices also won't really affect the user experience very much.  
  Configuring could be done on either specific mount points (just check if something is mounted there) or a device name.  
  **I can only talk about Linux, so other OSs may need other solutions.** On Linux, you can set up udev rules to ensure your device will always have the same device name. Then only these would need to be probed.
1. Is it really necessary to detect the GPS device on startup ? With other map software I sued so far, I did not always connect the device when I used the software. So probing could be delayed to the moment when the user wants to sync data. This would result in having to probe in less occasions.  
  But I clearly would prefer the "configure" solution.

**Comment by kiozen** [comment]
concerning 1: Users expect this to be plug-n-play. And as already explained you can not tell if a drive is a GPS device until you probed for it's content. The ticket was closed because of PR #174 that checks if a device is removable. If it is not removable it's not bothered any further. So I do not really see a reason why your hard drives are bothered unless you use an outdated version of QMapShack or your system reports hard drives as removable devices.

And no user want to setup udev rules or be bothered by some cryptic Linux/distribution way to handle usb devices. That's for sure. No one will appreciate a backdrop from the current plug-n-play approach to some peculiar cryptic configuration. 

concerning 2: If you have plugged in your GPS device before you start QMapShack you expect your GPS devices to be listed once you started QMapShack. As QMapShack missed the moment the udisk2 service sent the signal it has to iterate over all listed devices to make sure any connected GPS device is listed. 

If you are not happy with the situation you have two options:

1. Find a better way to reliably detect devices via plug-n-play and send a patch.
2. Disable the detection by Menu->Workspace->Setup Workspace. By that QMapShack does not care about devices anymore and you have to handle your devices just like any other drive.
