### ISSUE TITLE
Alternative Paths for routino control files.

### ISSUE THREAD

**Issue by jmfloyd** [Maproom/qmapshack#158]
**Is your feature request related to a problem? Please describe.**
Took a while to sort out where the folder where profile.xml file is located.  

The routino standalone router  will look in the /usr/shared/routino folder as well as the folder where the database is stored along with a prefix the same as the database.  The trouble with/usr/share folder for this is that the profile.xml cannot be readily modified by a user.

**Describe the solution you'd like**
Allow for checking for across various locations like the standalone executable does.  Especially a user controlled folder.

**Describe alternatives you've considered**
As above... yes the location can be modified in the configuration but this does not allow a project based variations.   Sometimes the profile may be closely related to the tagging (remapping) that routino uses to make the database simpler to query.

**Additional context**
Currently I have had to use root to modify the defuyalt profile.xml.  I have need to modify both the tagging and profile xml files order to allow routing along 4WD dirt roads that are tagged as tracks in Australia.  The default routing setup does not allow motor vehicles along tracks and using a cycle profile may put you in a very narrow track that is not suitable for a 4 wheeled vehicle.

Qmapshack was a great discovery I used originally for mapping my 1 week cycle trips through parts of Australia.  I now use it to record my 4WD trips through the country. Thanks

**Comment by kiozen** [comment]
Have a look at `CRouterRoutino::CRouterRoutino(QWidget *parent)`. The profile is set right at the startup of QMapShack. From that point on a routing request can be done at any time. 

If I recall correctly I once tried to do the initialization on each request. However it turned out that you can't re-initialize Routino. But that is quite a while ago. You might to verify that on your own. 

So it's a bit different than calling a stand alone app that makes the re-initialization by starting over and over again.
