### ISSUE TITLE
Crash with new/modified profile in Routino profiles.xml

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#217]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x] Did you choose a good title?

**Describe the bug**

* Copy the default Routino `profiles.xml` to the Routino database folder.
* Rename it to `prefix-profiles.xml` where `prefix` is the prefix of an existing Routino database.
* Find the line ` <profile name="bicycle" transport="bicycle">` in this file and change it to `<profile name="bicyclexxx" transport="bicyclexxx">`
* Start QMS.
* QMS crashes while loading the Routino databases with this modified profiles file.

**What have you done to circle down the problem?**

Crash was found when testing new possibility for user-defined profile files.

**To Reproduce**

see above

**Expected behavior**

Avoid crash and, if possible, inform user about infeasible profiles file. If user information not possible then don't show the wrong profile in the selection lists.

**Screenshots**

None

**Attachments**

None

**Tracebacks**

Not necessary.

**Desktop (please complete the following information):**

 - OS: Windows 10
 - QMapShack latest commit with user-defined profile files.
 
**Additional context**

None

**Comment by kiozen** [comment]
@jmfloyd can you please have a look?

**Comment by jmfloyd** [comment]
OK this was something that is in the original code that I had only just noticed but is not due to any of my programming.  I was going to raise an issue and sort out some code soon.

I am assuming that the user still had the bicycle profile selected in his gui, but he has renamed it in the profiles file.  This does happen, and would cause an error on initial load where it is calc'ing routes with the previous gui setup.

The case is this.
If you ask use a profile that isnt in the profiles file, routino returns a null ptr from Routino_GetProfile.  But the original code does not catch this and passes it on to the routing routines.  The docs state that qms must handle the default profile names so it is covered.  But it is easy to catch that missing case.  It is also suggested that qms should load the gui with the profiles that exist in the profiles.xml.  Routino can provide the list of profiles.

Must also do the following which is better as it catches the error.  I have been thinking of changing the loadProfiles to loadProfile, which also does the loadProfiles but also activates the requested profile and returns that to the calcRoute routines. Then the error can be caught and a message displayed.

John

**Comment by wthaem** [comment]
QMS still crashes in the same or a similar situation.

My test:

* Start QMS with clean profiles.xml (even user-defined ones). Routino settings point to an existing and correct database and profile. Up to here everything is ok.
* Add new Routino database folder (not yet known to QMS!) with user-defined and "broken" xxx-profiles.xml. This time the change was from

    ~~~
    <profile name="motorcycle" transport="motorcycle">
    ~~~

    to

    ~~~
    <profile name="motorcyclex" transport="motorcycley">
    ~~~

* QMS starts loading the new database folder and the"broken" xxx-profiles.xml file in this folder and crashes while loading.

**Comment by kiozen** [comment]
Hm, can't confirm that. I either get the message box telling me that the profile is broken. Or while routing if the profile name has been corrupted. But no crash.

**Comment by wthaem** [comment]
No message box and no error message in the log file. Crash can be reproduced.

**Comment by kiozen** [comment]
Strange, are you sure you are using the correct version? Can you set breakpoints and do a step by step analysis?

**Comment by wthaem** [comment]
Used commit

**Comment by kiozen** [comment]
well this is the correct commit.

**Comment by wthaem** [comment]
Here are my debugging results:

* Crash happens in CRouterRoutino.cpp, line 335 (within CRouterRoutino::loadProfiles):

    ~~~
    res = Routino_ParseXMLProfiles(profilesPath.toUtf8());
    ~~~

* My Routino version: 3.3.2
* `profilesPath.toUtf8()` seems to be correct. Thus, the crash is certainly a Routino issue and QMS can only be more careful at this point.

**Comment by kiozen** [comment]
So the crash is inside the Routino lib. I guess we can't do much about that.

**Comment by kiozen** [comment]
I close this for now as it is not really a QMapShack problem nor a problem for the normal use case. If the user is playing around with own profiles and corrupts the files everything might happen.
