### ISSUE TITLE
Option to set Visibility for multipleitems in Project View

### ISSUE THREAD

**Issue by prior-philip** [Maproom/qmapshack#226]
**Important Notice:**

**Do not delete any of the sections. Answer them. If you really**
**think they do not apply to you give a short statement. Feature**
**requests that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[y ] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

When reading in a GPS device with tons of tracks, it would make sense to set visibility of all tracks to OFF but the one track of interest. There is no option to toggle visibility of multiple items of a Project or device. A visibility toggle option on RMB would be great.
**Describe the solution you'd like**

Add the option to commonly toggle visibility of all items within ProjectView

**Describe alternatives you've considered**

Select desired items in the list and toggle visibility with LMB.

**Give a reason why someone else should spend time on that request**

Imagine a list of ~150 tracks within an small area, all are selected by default. How do you reduce the mess on the screen by narrowing it down to the one that you really want to see?

* The request solves a fundamental problem for everyone
* The request is of general interest for many users

It is of interest for all users with list >10Tracks per Project or attached device.

**Additional context**

![image](https://user-images.githubusercontent.com/68287405/87439738-69245380-c5f1-11ea-9f1c-267d23a218dd.png)

**Comment by kiozen** [comment]
This is very likely not happening. This request pops up occasionally. The answer is always the same:

* If we would implement this it has to be ok for every case and item. And this will fail. There are collections with a huge amount of items downloadable on the Internet. And users expect these collections to be loaded more or less in a snap. An example is Archie's Caravan and Camping list. This contains over 11000 waypoints. This will make 11000 check boxes to be maintained by the QT subsystem. No way.

* I can not emphasize it often enough: The workspace is not the database. Your problem arises because you are abusing the workspace as a database. It's not the intended use case to load everything in the workspace and then blend out everything but a few items. This is why there is a database and you can select single items to be loaded into the workspace. Keep in mind: every item in the workspace needs to be addressed by each operation. Having loads of items in the workspace puts stress on your system and slows down everything. Don't do it. Store your stuff in the database and load only the stuff you like to have visible into the workspace.

**Comment by kiozen** [comment]
As there is no real progress on the topic I close it for now.
