### ISSUE TITLE
Windows: adapt build scripts for 1.15.1 release

### ISSUE THREAD

**Issue by huirad** [Maproom/qmapshack#264]
**Windows: adapt build scripts for 1.15.1 release**

The windows related build scripts shall be updated such that they fit to the 1.15.1 binary release

[X] Did you choose a good title?

**Source repo and binary distributions shall be in sync**

Source repo and binary distributions shall be in sync such that everyone can reproduce the build

**Update the windows related build scripst as follows**

FindPROJ4.cmake: add support for proj 6.3
3rdparty.txt: improve references to licenses
copyfiles.bat: adapt to using Qt5.12.10, + proj 6.3 support+ improve references to licenses
QMapShack_Installer.nsi: adapt to using Qt5.12.10, + proj 6.3 support+ improve references to licenses

**Describe alternatives you've considered**
Upgrading to Qt5.15.2 and MSVC2019: In that case the offline help did not look so nice

**Give a reason why someone else should spend time on that request**

I will do it by myself, if you allow

**Additional context**

Windows binary installer for release V1.15.1.

**Comment by wthaem** [comment]
> Upgrading to Qt5.15.2 and MSVC2019: In that case the offline help did not look so nice

Could you please give an example/a snapshot of this?

Is there really a dependency between the offline help layout and the MSVC version? If yes, then there might be an issue somewhere in the CHelp*.* source code part.

I'm working with MSVC2019 and Qt5.15.0 for quite a while. Up to now, I didn't notice any layout problems when using the offline help with Qt assistant (I rarely open it from within QMS, but here too, I didn't notice layout problems). 

Thanks!

**Comment by huirad** [comment]
Hello @wthaem here come some screenshots with some annotations added in red color

First with QT5.12.10&MSVC2017, installed in C:\Program Files (no write access for me as regular user)
![grafik](https://user-images.githubusercontent.com/4027039/100552474-af6c0d80-3287-11eb-86da-9363cc2023a3.png)
Now the same when I am starting it from the temporary directory where I copy it before building the installer (read/write-access) 
![grafik](https://user-images.githubusercontent.com/4027039/100552521-f9ed8a00-3287-11eb-8efc-a99a860ed8f6.png)

First with QT5.15.2&MSVC2019, installed in C:\Program Files (no write access for me as regular user)
![grafik](https://user-images.githubusercontent.com/4027039/100552607-9d3e9f00-3288-11eb-8afb-e1e504808058.png)
Now the same when I am starting it from the temporary directory where I copy it before building the installer (read/write-access) 
![grafik](https://user-images.githubusercontent.com/4027039/100552649-c8c18980-3288-11eb-969d-df14370e3078.png)

So, somehow the Index is missing when I run the  QT5.15.2&MSVC2019 version, installed in C:\Program Files
But it is there, same as for the QT5.12.10&MSVC2017 version when I start it from the temporary directory.

I had the impression, that I have to run the help first in the temporary directory before building the installer.
Because then some of the Qt help index files are changed.
But I did this in both cases. So I cannot explain the difference.

Honestly, the QMS 1.15.0 installed version (QT5.12.8&MSVC2017) had the same defect as now observed with the QT5.15.2&MSVC2019 version.
I always wondered why nobody complained - not even you (I assumed that you alwys test the windows binary installers ;-))

I simply have neither the time nor any ideas to find out what makes the difference.
Maybe there are some subtle differences in the way I prepared the builds/installers.
Maybe it's due to the way I am testing (my test machine is my build machine, no VM's, no clean environment).
I am just happy that it now seems to work with the QT5.12.10&MSVC2017 installed version.

**Comment by wthaem** [comment]
Thanks for this information! If I'm not mistaken, I noticed this lack of content once in the past. It happened never again and thus, I didn't pay attention to it. I'll have another look at it.

**Comment by mitxel-m** [comment]
I have made some testing on this topic, following @huirad 's hints about write permission folders.

**On WIN10 on a VM.**

From the regular Qmapshack at C:\Program Files\QMapShack\

- Help works well for me, except 'String search'

From a copy installed in a folder with write permission

- Help works well, even the String search
- The first time you call help, a new subfolder is created at ..\QMapShack\doc\HTML ( the folder where the help files live). This subfolder is  called `.QMSHelp`and contains a file called `fts` that is a DB
- I have benn observing that this file does not change from one session to the next one

Well, I have copied that subfolder with its fts file to `C:\Program Files\QMapShack\doc\HTML` 
(win prompts to do it as adminisrator)  et voila. ! Now the 'Search string' also works on the regular QMS installed at  C:\Program Files\QMapShack\


**On linux Mint 19.3 cinnamon**

I had exactly the same problem: Help works well except String search

- On my system QMS help files are located at `/usr/local/share/doc/HTML`

- I have put there the same `.QMSHelp` folder with its `fts`file ( the same used on windows) and from now "Search string" is also working on Linux 

This is good news because I was missing the 'String search'



This said, a possible solution could be that the installation process itself includes the `.QMSHelp` sub-folder and its `fts` file along with the help files.  I know, it doesn't seem like an elegant solution, it's just a workaround

**Comment by huirad** [comment]
Hi @mitxel-m, thank you for your observation regarding the string search in the  offline help.
Please create a separate issue for this.
Then there is a chance to get it fixed in the next release.

The current issue #264 is only to get the source repo aligned again with v 1.15.1.

**Comment by wthaem** [comment]
There exists already #266!

**Comment by huirad** [comment]
Pull request https://github.com/huirad/qmapshack/tree/QMS-264 should resolve that issue.

**Comment by kiozen** [comment]
I do not see a PR yet. Is that intended?

**Comment by huirad** [comment]
Oh, I had the impression that pushing the commit automatically creates the pull request.
Is it now better with https://github.com/Maproom/qmapshack/pull/271 ?

**Comment by huirad** [comment]
Opdated pull request: https://github.com/Maproom/qmapshack/pull/272
