### ISSUE TITLE
Rename file called 'LICENSE' as 'GNU_License.txt'

### ISSUE THREAD

**Issue by mitxel-m** [Maproom/qmapshack#270]
[x] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

From version 1.15.1 the binary installer brings to the QMapShack root directory a file containing the text of the GNU license,  called `LICENSE` ( without any extension).

Users who previously installed the ECW and MrSid plugins already have a folder with the same name `license` in the QMapShack root. Therefore the installer cannot write the file called `LICENSE`and shows an error message. 

![](https://i.ibb.co/93y8vfM/rea-de-trabajo-1-014.png)

You can click on `Ignore` , the installer resumes and once finished, you can run QMapShack normally, but doing so the license file is missing in the QMapShack folder. 

**Describe the solution you'd like**

Rename the file with a more explicit name according to its content, and add the extension. For example `GNU_License.txt`

**Describe alternatives you've considered**

It could be renamed `LICENSE.txt`,  but in the repo there is already another file with the same name at `src/icons/geocaching/LICENSE.txt`

**Give a reason why someone else should spend time on that request**

The file named `LICENSE`was committed to the repo on 2 Apr 2019. The procedure to add the 3rd party plugins was included in the wiki earlier, and many regular users who have already followed the instructions in the wiki (and are not aware of this issue) would find the error message when running the installer with each new update.

**Additional context**

The license text is displayed when the installer is run. I don't know if the text is included as it is in the installer or is read from the file. May be some minor adjustments in the installer could be also necessary.

**Comment by kiozen** [comment]
The LICENSE file is there since the very beginning of the project. It's one of the must be there when it comes to the Debian quality checking.  And that is the reason why I wouldn't like to change the name in the source code repo. @huirad Maybe you can change the name to LICENSE.txt when you copy it into the Windows installer. Would that be possible?

On the other hand side this is more a problem of users manually copying files blindly into the program folder of QMapShack. Doable but somehow of the users responsibility and risk.

**Comment by mitxel-m** [comment]
> The LICENSE file is there since the very beginning of the project. It's one of the must be there when it comes to the Debian quality checking. And that is the reason why I wouldn't like to change the name in the source code repo. 

Ok. I was not aware of this detail. Therefore, there is no doubt that the file must remain with the name License in the repo.

>@huirad Maybe you can change the name to LICENSE.txt when you copy it into the Windows installer. Would that be possible?
> 
> On the other hand side this is more a problem of users manually copying files blindly into the program folder of QMapShack. Doable but somehow of the users responsibility and risk.

I also agree that the problem is on the side of the users who added add-ons to QMS on their own.  However when we wrote the way to do it in the wiki it was not done blindly, at that time the installer did not bring the `LICENSE` file to the QMS folder, and so the procedure was correct.

If you prefer I have no problem modifying the instructions in the tips and tricks section of the wiki, I can add one more step indicating that the `license` folder must be renamed to `licenses` to avoid this problem. 

Modifying the name of the file brought by the installer would also be a good solution that benefits even those who already have the plugins installed, that's why I proposed this solution. Of course, only if @huirad decides that it is possible without much work for him.

Please, don't worry too much about this, it is a very minor problem. Mostly the idea was to have it reported before anyone complains and to make clear that it is not a bug in the installer. 

If you decide that it is better to modify the instructions given in the wiki let me know, and I will do.

**Comment by huirad** [comment]
Hi @mitxel-m , @kiozen. 
The LICENSE file is written by the Windows installer since version 1.15.0 to comply with the Qt Open Source Obligations (https://www.qt.io/download-open-source): "Provide a license copy & explicitly acknowledge Qt use"
The license copy is the LICENSE file.
The Qt use is acknowledged in the file 3rdparty.txt

Sure, I can give the LICENSE file another name while still complying with the Qt Open Source Obligations.
You can assign me this ticket.

**Comment by mitxel-m** [comment]
@huirad thank you for your work and for taking this into account in the new scripts
