### ISSUE TITLE
Can' rename a route

### ISSUE THREAD

**Issue by Silicomancer** [Maproom/qmapshack#277]
**Describe the bug**

I want to rename a route but I can't.

**To Reproduce**

1. Create a project containing route
2. Right-click on the route and select "Bearbeiten" (in english modify/edit?)
3. A Dialog opens that contains an "Info" tab. Within this tab the name of the route is shown, styled like a link
4. Click on that link
5. Nothing happens (except the link style is removed from the name)

**Expected behavior**

I expected clicking on the link would open another dialog that allows renaming the project.

**Desktop (please complete the following information):**

 - OS: Kubuntu 20.04
 - QMapShack 1.14.0
 - Window Manager KDE

**Additional context**

Maybe there is a different way to rename a route. I couldn't find one. Pressing F2 and editing directly in the project view would be the easiest way.

**Comment by kiozen** [comment]
Simply click on that link and start to type/edit the name in place. No other dialog needed.

**Comment by Silicomancer** [comment]
LOL, yes it works that way. Thanks a lot.
I am developing software for 25 years but I have never seen something like that it any UI style guide. The behavior was totally unexpected to me. Don't you think a dialog (like when renaming a project) or even better some kind of line edit would be more intuitive?

**Comment by kiozen** [comment]
If you are a developer make a PR with a better solution to discuss it. From my point of view a pop-up dialog with the usual ok/cancel decorations is just unnerving. 

It might be part of one of your style guides but it will draw my visual focus from that line to another. For what? 
And all that decorations? Do I really want to use the mouse when typing? No I will use esc, left, right, enter. 
So why show all this stuff? Just because some style guide says so?

If we would stick to style guides we would still have Windows 3. Or do you require a style guide each time you want to evolve something? And is everything good that is in a style guide?

But you are welcome to improve stuff. If it hat subjective benefits compared to the current solution everyone is happy.

**Comment by Silicomancer** [comment]
I don't like dialog too. But then, why does renaming a project via a similar like open a dialog?

> And all that decorations? Do I really want to use the mouse when typing? No I will use esc, left, right, enter.
> So why show all this stuff? Just because some style guide says so?

Well it is up to you. I have other projects to take care of. And obviously you are a very good developer with a great product.

I would never expect something that is a visual link to behave like that. Without opening an issue I would have never figured out how to rename a route. Maybe it is just me. If you think this behavior is better than the conventional styles it is fine.
