### ISSUE TITLE
WMTS-based maps aren't restored correctly

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#285]
**Important Notice:**

**Do not delete any of the sections. Read what is requested.**
**_Replace(!)_ the instructions by your _answer(!)_. Bug**
**reports that are not properly filed might be closed without**
**further notice.**

**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x] Did you choose a good title?

**Describe the bug**

Maps displayed in QMS:
* 1 vector map
* 2 different maps from 2 different WMTS files.
    * WMTS filenames are different
    * Complete resource URL's are different
    * First parts of the resource URL are equal (wxs.ign.fr)
    * `Title` entries are equal: `<ows:Title>Service de visualisation WMTS Geoportail Publics</ows:Title>` 

Up to here everything is ok.

* Close QMS
* Restart it
* Displayed maps:
    * 1 vector map
    * **only** 1 WMTS map
    
The second WMTS map isn't shown.    

**What have you done to circle down the problem?**

The config INI file reveals the issue:

```
Views\View%201\map\active=f4a9483a924a28c05212eb3d65409249, 2c26d8c256d079312c5609718bf269e1, 2c26d8c256d079312c5609718bf269e1
```

i.e.: 3 maps have been displayed when closing QMS. **But:** 2 of them have equal "code"

Here is the complete rest of the map part the config INI file:

```
Views\View%201\map\f4a9483a924a28c05212eb3d65409249\opacity=100
Views\View%201\map\f4a9483a924a28c05212eb3d65409249\minScale=1e+12
Views\View%201\map\f4a9483a924a28c05212eb3d65409249\maxScale=1e+12
Views\View%201\map\f4a9483a924a28c05212eb3d65409249\showPolygons=true
Views\View%201\map\f4a9483a924a28c05212eb3d65409249\showPolylines=true
Views\View%201\map\f4a9483a924a28c05212eb3d65409249\showPOIs=true
Views\View%201\map\f4a9483a924a28c05212eb3d65409249\adjustDetailLevel=0
Views\View%201\map\f4a9483a924a28c05212eb3d65409249\typeFile=
Views\View%201\map\2c26d8c256d079312c5609718bf269e1\opacity=100
Views\View%201\map\2c26d8c256d079312c5609718bf269e1\minScale=1e+12
Views\View%201\map\2c26d8c256d079312c5609718bf269e1\maxScale=1e+12
Views\View%201\map\2c26d8c256d079312c5609718bf269e1\cacheSizeMB=100
Views\View%201\map\2c26d8c256d079312c5609718bf269e1\cacheExpiration=8
Views\View%201\map\2c26d8c256d079312c5609718bf269e1\enabledLayers=0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15
```

_Conclusion:_ Only 2 maps are saved with their details. Rule for generating the "code" fails to distinguish 2 different WMTS-based maps and should be improved so that 2 different WMTS files using different servers (resource URL's) get different "codes".

_Remarks:_
* Changing the title of one of the files slightly resolves the issue.
* There can be a QMS crash at the first QMS restart after the title modification! QMS can be restarted at the second or third attempt.

**To Reproduce**

see description above

**Expected behavior**

All maps should be shown after QMS restart

**Screenshots**

None

**Attachments**

None

**Tracebacks**

None

**Desktop (please complete the following information):**

 - OS: Windows 10
 - QMapShack Version 1.15.2
 

**Additional context**

None

**Comment by mitxel-m** [comment]
I can confirm this.

I have activated two .wmts that fulfill what wthaem has said, this is, both them are from the same origin (service), but with different content (layer).  Then close QMS and can't restart.

The only way for me to restart QMS has been to edit the .conf file, to delete the map entry.  In the .conf file only one map entry was kept.

In a second test, I activated two wmts of the same origin, and then left only one of them active . Close QMS and  on the next start the loaded WMTS was not the expected one, but another one from the same origin.

I have checked the wmts files

I guess that  the `Title` label pointed by wthaem is under `<ows:ServiceIdentification>`
```
 <ows:ServiceIdentification>
    <ows:Title><![CDATA[IDENA - Infraestructura de Datos Espaciales de Navarra]]></ows:Title>
```
There is another  `Title`  label under  `<Layer>`

```
 <Layer>
      <ows:Identifier>mapabase</ows:Identifier>
      <ows:Title>Mapa base</ows:Title>
```
May be this one could be used to compose the key? Not sure, because there are also wmts services that serve more than one layer in a single wmts file.

I have tried with wmts provided by IDENA, the authority in Navarra, one of the Spanish regions that has its own mapping service.

I have prepared a .zip file containing several files for testing.:
 - The so called IDENA_full.wmts is a unique wmts file serving several layers.
 - The rest of them are wmts calling one layer individually ( Topo; Ortho; Base map)
 - There is also included a  .gpx file with a wp to land in the region

Download[ IDENA_wmts_test.zip](https://mega.nz/file/ZNsERbZL#01kHMoa_iSYORDOGvnOXMucjoCaSgh-l2-3Qs423vtM)

Remark: In some cases it is necessary to have these wmts that call for a single layer in order to be able to handle the visualization order, the scale range, or to apply transparencies individually,   This would not be possible with a single wmts calling several layers.

 Let me know if I can help with testing.

**Comment by kiozen** [comment]
To identify maps a MD5 hash is calculated over the first 1024 bytes of a map file. If these bytes are identical the same key is derived. Could you please check if that is the case?

I checked with the IDENA files and the first 946 characters seem to be the same when comparing IDENA_full.wmts with the other ones.

**Comment by wthaem** [comment]
In my case the 2 WMTS files are equal up to the hex address 9b0!

**Comment by kiozen** [comment]
Which explains it. I can increase the threshold a bit. But it has to be limited as we do not want to hash files of several GB.

**Comment by kiozen** [comment]
please review and test

**Comment by wthaem** [comment]
No problems any more with my pair of files! Thanks! 

BTW: both files have the same rather long abstract node right at the top of the file. Thus, the difference in the server URLs appears quite late.

**Comment by mitxel-m** [comment]
Thanks! 
Now it works for me too.
