### ISSUE TITLE
Ability to add custom online router endpoint

### ISSUE THREAD

**Issue by flohw** [Maproom/qmapshack#328]
**Choose a good title**

What is a good title?
The title will be listed in the changelog when the issue is fixed. Do
you think someone else would understand what's fixed or done from your
title? Does it really name the real topic of the issue?

[x] Did you choose a good title?

**Is your feature request related to a problem? Please describe.**

Router might not feet the needs

**Describe the solution you'd like**

I would like to be able to add my custom router with custom api endpoint.

**Describe alternatives you've considered**

Using routino but the file size is huge and I need to update them frequently.

**Give a reason why someone else should spend time on that request**

It would be a more flexible software. Any user can use the routing system he wants with the behavior he already might know.

**Additional context**

I would like to use [IGN (France)](https://www.geoportail.gouv.fr/carte) routing on the right you have a key, then "Calculer un itinéraire". Or maybe [Michelin](https://www.viamichelin.fr/web/Itineraires) one if it's available publicly.

I hope this would be possible. Thank you :slightly_smiling_face:

**Comment by kiozen** [comment]
I added the volunteer tag to the request however I doubt that any one will do. Why?  Because it's just another one of these feature requests spending at most 5 minutes to ceate but asking for several man days of work. Without providing that minimum effort of pre-work that could be done.

No one, really no one, would like to start that job without a link to the services API, a rough concept how you want to unify different REST APIs of different routing services. And what credentials and other (legal) prerequisites it would take to use the service. And that is a job you do not need to know c++ for nor have to find your way into the code. It is just that chunk of work anyone could do and it would show some respect for the work and time requested to be spent.

If you want someone else to do the job for free provide as much information and pre-work as you can. You would do the same if you would ask a craftsman friend for free help in real life.

**Comment by flohw** [comment]
Maybe if you ask what further information you need I would be happy to provide them?
I provided two examples, I thought I might be sufficient to know if it's doable or not.

I would be more than happy to help on the project, even if my c++ knowledge are far behind...
Just close the issue if you don't care or won't do it anyway but please, don't be rude with people which make the effort to create a feature request or a bug report with more than "it don't work" as description... It doesn't help anybody and they only want to leave...

**Comment by kiozen** [comment]
Well your feature request comes close to the "it does not work" category. That's why I gave the feedback in the first place. It boils down to:

"I want to use all kinds of online routing engines. Especially that one (link to web frontend)."

I already asked you to provide a link to the service's API definition. To provide a rough concept on how you would like to unify the different REST APIs of different routing services. And what credentials and legal prerequisites it does take to use these services. 

How to improve?
If you have a look at other feature requests in this tracker you will find some  very good ones, some mediocre ones and some that are simply demanding without providing much information. If you have a look at the feature requests that ended in a successful pull request you will notice that many have been implemented by the requester. And those implemented by someone else are usually quite well defined. 

Conclusion: If you want something from someone else provide as much pre-work as possible to minimize their effort. Especially if you want something for free. Else you risk to annoy the person you are asking.

**Comment by flohw** [comment]
Sorry but your answer was unclear to me... It was only an idea to know if this is possible then push it further together to achieve the point. Maybe the issue was not clear about this either.

I will provide api endpoints I mentioned and an idea to unify the different api's response.

**Comment by kiozen** [comment]
As there is no progress for a long time I close it for now.
