### ISSUE TITLE
New Points land always in the first project in list

### ISSUE THREAD

**Issue by Kettenknecht** [Maproom/qmapshack#394]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

If you create a new waypoint it always shows up in the first project in the project list. Regardless if the project is checked or not, or if another project is selected/highlighted.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

Tried to uncheck projects, or highlighted the project the new waypoint should belong to.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

- Highligtht the project you work on
- Create a new waypoint
- Recognise that the waypoint always shows up in first project of the list

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

- The waypoint should be createt in the highlighted project

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: MacOS 11.3.1
 - QMapShack Version:   1.15.2

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by mitxel-m** [comment]
@Kettenknecht 

From your reportt, it looks like you have assigned the first project as  'Active project'. Can you check if it appears marked with a yellow star?

Take in mind that QMS does not create new wp's in the project you have highlighted. It works in a different way, QMS automatically creates the new elements in the project you have marked as active project.

The active project is assigned from the context menu and is marked with a yellow star.

If there is no project marked as active then QMS will ask every time where you want to save each new wp, which is annoying. That's why the function to mark a project as active was created.

You can read more about it by clicking F1 in QMS, then find "Active Project' in the index.
and the same on the wiki:

https://github.com/Maproom/qmapshack/wiki/AdvProjActions#user-content-active-projects

**Comment by Kettenknecht** [comment]
Oh. thank you very much. pebcac :)
