### ISSUE TITLE
Can't increase the duration of the cache beyond 14 days and its size beyond 1 Go.

### ISSUE THREAD

**Issue by ventoux84** [Maproom/qmapshack#468]
This is annoying when I want to plan a long stay where I have no internet connection.
I would like to be able to store the tiles of a WMS inline map covering the area where I will be hiking.

![Qmap](https://user-images.githubusercontent.com/56974650/145841102-5c8ba83d-88bc-445e-a307-b980c439eb27.png)

### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: [e.g. OS X, Debian, Suse, Windows]
 - QMapShack Version:   [e.g. 1.13.1]
 - Window Manager:  [e.g. KDE, GNOME]

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by kkarsten62** [comment]
Hmm yes, this is a very interesting use case to use the cached tiles in a kind of offline mode. My interest is more on performance when displaying the tiles and to have the tiles cached for printing dialog.

But what is the next good values for data size and expiry date? I am quite sure if we increase let say to 2 GB and 3 weeks then the next user is requesting soon for 3 GB and 4 weeks :-)

So may be on option could be to have 2 combo boxes with some predefined values and one of them is "unlimited". But unlimited is dangerous because it can explode your hard disk. So maybe a warning/info message could help to inform the user when selecting the "unlimited" option that there is a risk for uncontrolled data increase on the hard disk and/or old data. And an additional button "Delete Cache" could also help.

***ComboBox Cache***
250 MB
500 MB
1 GB
2 GB
Unlimited

***ComboBox Expiry date***
1 Day
7 days
14 Days
4 Weeks
3 Months
Unlimited

But let wait what other people from the community will say before spending energy in such kind of development. I guess that kiozen has a dedicated opinion on that.

**Comment by ventoux84** [comment]
Yes, or let the user enter the value he wants.

**Comment by ssmlc** [comment]
Comment from the community: 
I was also looking for an unlimited expiry date option.

Other suggestions for UI:
- Let users type in whatever they want (e.g. 15 days, 36500 days; 2500 MB, etc.; 0 days could delete the cache or be unlimited)
- One box to type in a number (e.g. 3) next to a combo box (days, weeks, months, years, unlimited; MB, GB, unlimited)

**Comment by kiozen** [comment]
I wonder why you do not install map data locally if you want to be independent from the internet. You can have your own tile server locally as described here:

https://github.com/Maproom/qmapshack/wiki/DocBasicsMapDem#mapsforge-maps

Or you find/create  some  maps in the GEMF format which is more or less a tile container.

What you try to do here is to create some TMS map download tool thru the backdoor.

**Comment by ventoux84** [comment]
> Or you find/create some maps in the GEMF format which is more or less a tile container.

indeed, it's a workaround but it requires more preparation.
With Mobac, I can make a .gemf file (osmdroid) of the tiles I use.

**Comment by kiozen** [comment]
It's not a workaround it's the way the cookie is crumbling. If you want offline maps you should use offline maps. The only reason why you want to abuse the cache is that you do not want to spend the time to prepare an offline map.  :wink: 

See it as a benefit. Instead of starting into the wild with a Swiss map cheese you have a complete map without holes you can rely on.

**Comment by thefoster** [comment]
> It's not a workaround it's the way the cookie is crumbling. If you want offline maps you should use offline maps. The only reason why you want to abuse the cache is that you do not want to spend the time to prepare an offline map. wink
But e.g. Google Hybrid/Sat isn't a real offline map, nevertheless i'd like to "abuse" that feature to act like an offline map, at least for some areas that don't have a similar grade of detail about the terrain (as Google Maps).
> See it as a benefit. Instead of starting into the wild with a Swiss map cheese you have a complete map without holes you can rely on.
Agreed for standard maps, but sometimes one may prefer the details from Google cached for a certain area.
Ideally you could choose an area (let's say 20x20km) and right-click "download/cache" this area with maximum detail level.

Right now you'll have to manually zoom in/out all of that area manually to be sure that it will be cached, which is very annoying.
