### ISSUE TITLE
Add alpha transparency based hillshading

### ISSUE THREAD

**Issue by JFritzle** [Maproom/qmapshack#483]
### Is your feature request related to a problem? Please describe.
[comment]: # (A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] )
Currently implemented grayscale hillshading algorithm behaves as follows:  
The more hillshading magnitude is increased the more hillshading overlay gets opaque, showing finally a very impressive elevation model of landscape.

However, if opacity slider is totally at the right side, underlying map becomes invisible. The more slider moves towards the left side, the more map becomes visible, but always behind a gray haze. To reduce this gray haze, slider must move further to the left. Unfortunately, hillshading impression gets then weaker and weaker and finally disappears. Thus making it impossible to have an impressive hillshading effect and at the same time see the underlying map.

Current grayscale based hillshading where underlying map is nearly invisible:
![Hillshading with shades of gray](https://user-images.githubusercontent.com/62614244/153586243-8a252f06-7ed8-4d15-a138-ebf3bdfa04c5.jpg)

### Describe the solution you'd like
[comment]: # (A clear and concise description of what you want to happen.)
I would like to have the choice to be able to switch between currently implemented grayscale based hillshading algorithm and an alpha transparency based algorithm, where hillshading overlay becomes the more opaque the steeper the slopes and becomes the more transparent the flatter the slopes and is totally transparent in the plain. Thus making the underlying map shining through.

### Describe alternatives you've considered
[comment]: # (A clear and concise description of any alternative solutions or features you've considered.)
-

### Give a reason why someone else should spend time on that request
[comment]: # (Keep in mind that you ask others to spend their spare time for your request. Good reasons are if you are able to prove that the request solves a fundamental problem for everyone, or the request is of general interest for many users. Bad reasons are you just want it to have that way, or argue that software xyz does it.)
I am convinced that many QMS users would deploy this new feature as soon as it becomes available.

I for myself have already implemented the few necessary stuff into a clone of QMS dev branch. Therefore, I believe, the time to spend for adding this feature will be short and will probably be restricted to reviewing my code, easily merging into existing code and translating few texts to all languages supported by QMS.

Switching between existing grayscale based hillshading and alpha transparency based hillshading is realized by one single additional check button. Switching takes effect immediately. Thus, both hillshading methods can coexist.

If proposal for this feature is accepted, I am willing to contribute my enhancement.

Alpha transparency based hillshading with same opacity slider and magnitude setting:
![Hillshading with alpha transparency](https://user-images.githubusercontent.com/62614244/153586513-969072a5-0635-4315-b031-752bffa9d7ca.jpg)

### Additional context
[comment]: # (Add any other context or screenshots about the feature request here.)
-

**Comment by mitxel-m** [comment]
@JFritzle,  this looks good. 

I'm also curious about something like this, but with a different approach. I think it would be better if it wasn't specific to hillshading, but rather a layer-wide setting that would apply to hillshading as well as the other renderings: slope, elevation, and the newest colour by height. 

In fact it is a similar problem for all of them, even with medium transparency values the basemap can look washed out. 

I have been tempted to propose something like this before, and I have been reading about the qt methods for blending raster images [here](https://doc.qt.io/qt-5/qml-qtgraphicaleffects-blend.html). But I don't know much about coding then I was still very unsure about it and whether it is applicable to map layers and DEMs.

I think hillshading is a 1-band 8-bit image. How do you get what you call alpha-based transparency?   it looks like you have overlayed the hillsade image with the burn method.

Imagine, if a control to set how the layer is blended could be implemented (burn, multiply,...), that would solve your problem with hillshading and also improve the other DEM renderings.

And even more, the same control could be used for raster maps. 
One use case is a topo base raster map with contour lines, and overlay an orthophoto.Normally transparency is applied to the orthophoto so that you can see some of the contour lines, but they appear washed out. By applying the multiply effect to the orthophoto layer, the lines and text on the base map would be perfectly dark.

IGN topo raster + IGN orto (multiply / opacity 70%)
![](https://i.ibb.co/1ms4K1f/pantallazo-028.jpg)

Your proposal has triggered me to comment this mainly because I think it's important to think very well where to place a control like that. and maybe it could be in line with what you have developed.
:-)

**Comment by JFritzle** [comment]
You will find 5 modified files at https://github.com/JFritzle/qmapshack/tree/QMS-483/src/qmapshack/dem

**Comment by kiozen** [comment]
As I expected, it's loosing details.

![shading_w_transparency](https://user-images.githubusercontent.com/54329441/153713744-4fe4fbe7-798a-4789-94c3-9b4d2e11bad5.png)
![shading_wo_transparency](https://user-images.githubusercontent.com/54329441/153713745-380f59b5-58e5-4b1c-9b3f-acd7542ebf04.png)

So it's original colors vs. details. Worth it?

**Comment by JFritzle** [comment]
I have checked the slopes at map location:
![153713745-380f59b5-58e5-4b1c-9b3f-acd7542ebf04_mod](https://user-images.githubusercontent.com/62614244/153717281-1db84464-8a36-4b1a-8ecd-41afe99c7949.png)

Gray value in area 1 appears at least to my eyes nearly the same as in area 2 which lets me assume, that landscape in both areas is similarly steep. But as you can check yourself, there is a notable difference in slope. With 1" DEM data by Sonny S, slope in area 1 varies between 0 and 3 degrees and slope in area 2 varies between 20 and 30 degrees. Thus the information content of the "detail" screenshot isn't more valuable for me than the information content of the "original colors" screenshot.

I agree that details may get lost here and there, because blending to light is much less spectacular than blending to dark especially over mostly bright colored maps. But after my opinion gain of map visibility outweighs the loss of slope details.

And: Having the choice between "details" and "original colors", no one will loose their favorite hillshading setting.

**Comment by kiozen** [comment]
Can you please push your latest changes so we can try them.

**Comment by JFritzle** [comment]
You will find 1 new modified file IDem.cpp at https://github.com/JFritzle/qmapshack/tree/QMS-483/src/qmapshack/dem

Not relevant for testing, but method is still called `IDem::transparentHillshading` while it should be better called `IDem::transparentSlopeshading`.

The term _slope shading_ is mentioned e.g. at https://blog.mastermaps.com/2012/06/creating-color-relief-and-slope-shading.html. There is also a link to an article how to combine slopeshade, hillshade and color relief into a single map image which were nicely to have.

**Comment by JFritzle** [comment]
Original hill shading and new (transparent) slope shading are now independent of each other and each layer can be enabled individually or together. Slope shading layer is above hill shading layer and below other additional dem layers. 

Each layer has it's own slider for scaling:
![Bildschirmfoto von 2022-02-14 15-30-49](https://user-images.githubusercontent.com/62614244/153887464-24ed4e85-ff60-4744-8668-caebb17de69f.jpg)
Changed files have been pushed.

**Comment by kiozen** [comment]
That's better. It preserves the old behavior. I would expect the slope slider to be reversed. The more it is on the right side the stronger (darker) the shading will be. But that might be dependent on the spectator.

**Comment by JFritzle** [comment]
- Reversed slope shading slider. The more it is on the right side the stronger (darker) the shading will be.  
- Increased maximum slope shading scale factor to allow for increased relief on flatter terrain.
This allows full opacity to be already achieved at a slope angle of 30 degrees.
- Now use QImage::Format_Alpha8 for slope shading layer's image format

Ready to create pull request?

**Comment by kiozen** [comment]
Sure open a PR and I will have a closer look into the code etc.
