### ISSUE TITLE
Color according to altitude (not gradient)?

### ISSUE THREAD

**Issue by think-nice-things** [Maproom/qmapshack#49]
Hi
dem files can be used to do coloring of hills according to gradients.
I didn't find how to color according to altitude.
Having mountains beeing colored above a configurable altitude would be mostly useful when doing aviation planning to check if the planned flight altitude is above the mountains.

**Comment by think-nice-things** [comment]
I implemented myself and just created a pull request.

See this screencast for demonstration, note how the elevation limit in the spinbox is changed with the mouse wheel.

![2019-11-01_QMS_ElevationLimit](https://user-images.githubusercontent.com/4885370/68059184-c85c6500-fcfb-11e9-842b-93fb08c3160c.gif)

**Comment by kiozen** [comment]
Nice! Animated GIF.

Btw, as this is another ticket that totally ignores the template, please do so in the future. I will have to close these tickets as they are a bad example and encourage others to do the same. This will end up in the same chaotic ticket style as we had on BitBucket. That's why I will enforce it.
