### ISSUE TITLE
Syncing GIS data between multiple computers

### ISSUE THREAD

**Issue by grothesque** [Maproom/qmapshack#532]
### Is your feature request related to a problem? Please describe.
I use multiple computers on a daily basis.  In my particular case the file systems are synchronized using the tool Unison, but other people are using rsync, git, Syncthing, or something else.

Since databases are complex files that can grow up to a huge size, they are not ideal content for such file-system synchronization tools.  However, it seems to me that the use of sqlite-databases in qmapshack is difficult to avoid if one wants to curate a large number of GIS items.

### Describe the solution you'd like
It seems to me that an alternative "database" backend that stores data not in a single database file but rather in a directory tree filled with, for example, GPX files, would lend itself better to synchronization.  This would be also a more transparent way of storing data - it would be possible to access the GPX files directly without using qmapshack.

### Describe alternatives you've considered
One could keep the qmapshack databases on a share that is synced in real time.  But this requires permanent network access and it may be still suboptimal in terms of performance: a small change to a large database file may not always be transmitted efficiently by the synchronization software. 

### Give a reason why someone else should spend time on that request
I think that syncing data between multiple computers is a problem that affects an increasing number of people.

**Comment by kiozen** [comment]
- Why don't you use a remote MySql database?
- Your "alternative database backend" sounds like a file system. Why don't you use it?

This feature request is quite fuzzy and is not very appealing to be considered. 
https://github.com/Maproom/qmapshack/wiki/DocFaqOpenSource#I-really-want-that-feature-please-add-it

**Comment by grothesque** [comment]
Thank you for the quick reply.

> Your "alternative database backend" sounds like a file system. Why don't you use it?

Exactly, I would like to store and curate my GIS data in a file system and not in a database that is opaque to other GIS software and creates problems for synchronization.  However, in my understanding, qmapshack does not support using the file system very well (in contrast to using a database), since there is a database widget, but no comparable file system widget.

The qmapshack database widget allows to browse a huge collection of GIS data.  With a single click it is possible to add and remove items to the workspace.  In contrast, using the file system requires opening files using a file dialog and then removing them from the workspace.  This is significantly more cumbersome than using a database.

I have the impression that qmapshack uses databases as custom file systems.  Wouldn't it make sense to better support using the file system directly?  Consider some photo management software.  There, the actual photo files will be stored in the file system and not in a database.  I think that similar considerations apply to qmapshack as well.

> Why don't you use a remote MySql database?

- A remote database requires a constant reliable network connection and creates a single point of failure.
- This requires quite complex specific configuration for just one piece of software.
- The database is opaque to other GIS software.  I do not see the rationale for storing what essentially are GPX files inside a database that replicates a hierarchical file system.

**Comment by kiozen** [comment]
To maintain a file system your OS provides enough tools. No need to implement that in QMapShack. With QMapShack you can load GIS data from the file system and store GIS data to the file system.

The benefit of a database compared to a filesystem is:
* Search your projects by metadata 
* Stored information independent from a folder. This allows more flexibility in linking projects to folders.
* For many users, except you: Have a single file instead of many.

If you do not need these benefits, stick to the file system. Nothing forces you to use the database. QMapShack works well without. Simply hide the docker widget.

GPX is an exchangeable file format but is not very good to store GIS data with the features QMapShack provides, e.g. an edit history that can be reverted. And all kind of additional information, that is not part of the GPX1.1 specification, has to be stored as proprietary extension making the files less exchangeable than the name implies. This is why QMapShack uses it's own binary format to store GIS data. All projects are stored in the database by this binary format along with metadata.

I do not really see the benefit in having all projects in single files in a file system and additionally maintain a database to handle these files in QMapShack via the database docker widget. I see great peril in that, as less knowing users will start to edit/move/ delete these files manually. Therefore the database will be constantly broken and we will have bug reports.

**Comment by grothesque** [comment]
Thanks for the explanation.  Having read in https://github.com/Maproom/qmapshack/wiki/DocGisDatabase that

> The data in the database is grouped in folders. Blue folders are for grouping several projects. Green folders are like projects. Think of them like a GPX file.

I had the impression that QMS databases are little more than non-standard file systems of GPX files.

I still think that a widget that provides a view of a portion of the filesystem in a way that is similar to the current database widget would be useful.  (Features like search and undo do not really seem to require a database as well.).  However, I unfortunately lack the time to contribute myself (have own projects to take care of).

The purpose of this issue has been to point out some impressions of a recent user.  Please consider updating the documentation (for example taking snippets of what you wrote above) to better explain the purpose of databases in QMS.
