### ISSUE TITLE
Map not redrawing when realtime GPS position is updated

### ISSUE THREAD

**Issue by gskjold** [Maproom/qmapshack#570]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)
Using bluetooth GPS, shared to qmapshack with
```ncat -v -l 10010 < /dev/rfcomm0```
Position, bearing and speed is constantly updated in the realtime view and the arrow shows on map, but the position and direction of the arrow is not updated unless you drag, zoom or toggle fullscreen. Also, does not seem to center on position, although this is ticked.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)
Have been digging around in wiki and closed issues, but could not find anything similar.

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Connect with GPS as described above
2. Configure realtime GPS TCP/IP source

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)
Arrow on map is updated when position or bearing changes. Also expect map to center on the arrow when that tickbox is ticked in realtime config.

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

### Desktop
[comment]: # (please complete the following information)

 - OS: Ubuntu 22.04.1 LTS
 - QMapShack Version: 1.16.1, as shipped with Ubuntu
 - Window Manager:  X11 with Gnome3 (Wayland disabled, but have tried enabled as well)
 - Graphics adapter: Mesa Intel® HD Graphics 4000 (IVB GT2)

### Additional context
[comment]: # (Add any other context about the problem here)
I hope my description makes sense. Let me know if you need anything else.

**Comment by gskjold** [comment]
Did some research on my own, turns out my gps has three digits for fractional seconds. Changed the format here: https://github.com/Maproom/qmapshack/blob/e59379ba989a40cd709ee705216ab11a1e1b41dd/src/qmapshack/realtime/gpstether/CRtGpsTetherInfo.cpp#L386 to "hhmmss.z" and fixed it. Not sure what is the best option for https://github.com/Maproom/qmapshack/blob/e59379ba989a40cd709ee705216ab11a1e1b41dd/src/qmapshack/realtime/gpstether/CRtGpsTetherInfo.cpp#L347 , but I'm just keeping my solution for now, maybe I'll return to it at a later point

**Comment by thefoster** [comment]
Here (Kubuntu 22.04) i first thought that my Ublox 7 and 8 don't work with QMS because the devices don't emit GPRMC/GPGGA but instead GNRMC/GNGGA.
But like in your example it is also about the amount of decimal:
simulation (gpsfeed+)
$GPRMC,065324,A,3759.9647,N,02400.0485,E,36.8,40.2,020123,5,E,A*04
ublox8
$GNRMC,195543**.00**,A,5216.22732,N,01032.419**00**,E,0.468,,070123,,,A*66
A pull request should be good for all ublox-users on Linux.

**Comment by gskjold** [comment]
Added a PR with the changes I did locally

**Comment by thefoster** [comment]
After having trouble setting MainTalkerID, at least i managed to set "ubxtool -d GLONASS" and got rid of GNRMC/GNGGA as default. Nothing changed in QMS, so it is more likely that i do have exactly the same issue as you with the amount of decimals.
Haven't found any option in gpsd yet to handle/change that and can't compile QMS myself because of proj4 (v8) incompatibilities.

**Comment by thefoster** [comment]
Just not to confuse anyone, my issue is about the amount of decimals in position data, not time data like in this issue.
