### ISSUE TITLE
Missing/Failing BRouter log window

### ISSUE THREAD

**Issue by wthaem** [Maproom/qmapshack#623]
### Describe the bug
[comment]: # (A clear and concise description of what the bug is)

There is a start/stop icon for the activation of the BRouter offline routing engine. Clicking this icon should start the engine and display `running` in front of the icon. At the same time an additional icon for opening a log window should appear.

In most cases, clicking the start icon changes the above-mentioned text and pops up the log icon only for a very short moment.

### What have you done to circle down the problem?
[comment]: # (Did you compare to previous versions? What versions? Did you check if others have the same problem?)

### To Reproduce
[comment]: # (List the steps to reproduce the behavior)

1. Go to BRouter offline routing
2. Click on start/stop icon
3. See described behavior

### Expected behavior
[comment]: # (A clear and concise description of what you expected to happen)

The new text and the log window icon should be permanently visible.

### Screenshots
[comment]: # (If applicable, add screenshots to help explain your problem)

None

### Attachments
[comment]: # (Can you provide an example file to trigger the problem?)

None

### Tracebacks
[comment]: # (Add your backtrace below if you have one. If QMapshack crashes the fastest way to get help is a backtrace.
For Linux see: https://github.com/Maproom/qmapshack/wiki/TroubleShooting#create-a-backtrace-of-a-crash-on-linux.
For Windows it would need a debug build and running QMapshack in Visual Studio.)

None

### Desktop
[comment]: # (please complete the following information)

 - OS: Windows 10, BRouter 1.7.2
 - QMapShack Version:  1.17.0
 - Window Manager: 

### Additional context
[comment]: # (Add any other context about the problem here)

**Comment by kiozen** [comment]
@ntruchsess can you please have a look?

**Comment by ntruchsess** [comment]
> @ntruchsess can you please have a look?
If it's not some kind of windows-specific behaviour this behavior might be caused by a simple error during brouter-startup in combination with a racecondition in the code. As it is not easy to distinguish in between normal shutdown and java terminating due to an initialization-failure of the java-program running within the jvm I used a QTimer that would expire after 200ms and any transition from process-state 'Running' to 'NotRunning' was taken as a normal shutdown. Whenever an initialization-error resulting in termination of the java-process would occur _after_ expiry of this timer the error would be ignored silently. I suppose this is what is happening here.
in #632 I replaced that timer by a simply tracking the stop-action using a boolean flag. Now every termination of java that is not triggered by clicking the start/stop-button will trigger display of the log-window.
It's possible there are other issues - e.g. it might be the event clicking the start/stop-button is delivered multiple times. In such a scenario brouter would just start and stop right afterwards not showing any error. But if there is any other issue with startup #632 will ensure the error is displayed regardless how long it takes to startup the process.
