### ISSUE TITLE
Feature Request: Route Optimization

### ISSUE THREAD

**Issue by WST1811** [Maproom/qmapshack#68]
**Is your feature request related to a problem? Please describe.**
I got a lot of Waypoints (20 to 25 or more) and want a Route/Track with the fastest Way between Start and End with touch all Waypoints. Now I have to sort the waypoints in the order in which they should optimally be approached.

**Describe the solution you'd like**
Here an option would be nice to have an automatic calculation from waypoint 1 over the other points to the last waypoint without having to specify the best order.

**Describe alternatives you've considered**

**Additional context**
Is this better feature request then #67?

**Comment by pingurus** [comment]
The problem you are trying to solve is also called the Traveling Salesman Problem. Since QMapShack doesn't do the routing by it's own, we would need a router that is able to solve this problem. 

If you find a router, that is able to solve the TSP and has an API that QMS can use, I am sure the feature can somehow be fitted into QMS. However someone needs to implement this. If you can code C++ the fastest would be if you do it yourself. Since this is nothing I will use in near future, I must say I'm not too keen to implement it. However, if you provide a good preparation it might well be, that I will implement that feature sooner or later, since I do think that it might be a useful feature.

**Comment by WST1811** [comment]
Thanks for answer. I don't know if this is what you need and you can use the API: 
https://openrouteservice.org/dev/#/api-docs/optimization/post
https://github.com/VROOM-Project/vroom/blob/master/docs/API.md

And/or this: https://www.graphhopper.com/blog/2019/05/17/getting-started-with-the-optimization-api-traveling-salesman-problem/
