### ISSUE TITLE
Online map retaining duration is lost when deactivating map

### ISSUE THREAD

**Issue by pingurus** [Maproom/qmapshack#95]
**Describe the bug**
When you enable a tms map, you can set the duration in which the tiles remain valid (Verfallszeit (Tage)). This information is lost once you deactivate the map.

**To Reproduce**
1. Open a tms map
2. Edit the "Verfallszeit"
3. Deactivate the map
4. Reactivate the map

**Expected behavior**
This information should be retained. Also, it'd be great if the user could set an arbitrary amount of time. (In my case I have some topographic maps I find pretty looking at and the information on those probably won't change in the next years (at least on the zoomlevels I look at) so it is just unnecesarry waiting time until those tiles are loaded and in addition I can't view them when offline)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - QMapShack Version1.14.0

**Additional context**
Yes, this might be kind of a feature request. @kiozen feel free to edit the tag, I'll adapt the content to the other form.

**Comment by kiozen** [comment]
QMapShack needs a single file to load a map. And as a rule it's not allowed to change that file. Would be possible with *.tms files as this is proprietary to QMapShack but changing *.img or *.vrt would be a disaster. So there is no way to store stuff along with the map.

That information is stored in `.config/QLandkarte/QMapShack.conf`. Each active map has it's hash and the information is stored under the hash. If the map file changes the hash changes. This and testing a lot of maps would spam the config file over time. That's why QMapShack cleans up the list of maps limiting it to the list of active maps. If a map becomes inactive the user configuration gets lost.

The only way to store the configuration of a map is to store the map view.

**Comment by pingurus** [comment]
> Each active map has it's hash and the information is stored under the hash. If the map file changes the hash changes. This and testing a lot of maps would spam the config file over time. That's why QMapShack cleans up the list of maps limiting it to the list of active maps. If a map becomes inactive the user configuration gets lost.

How about deleting the information from the .conf file after the map retetention duration is over? Yes, this requires more checking but would be much more convenient if, for some reason, I want to access that map when being offline and I deactivated it for some time for some other reason.

**Comment by kiozen** [comment]
This requires periodic cleanup of the configuration file. This is not the intended use case of such files.

Imho you have to life with it when using online maps. They are not the appropriate format for offline use. Use a GEMF maps, GeoTiff or Garmin maps for offline use.
